version: '2.2'

services:
  web:
    build:
      context: .
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pubsub

  worker:
    build:
      context: .
    command: ["bin/rails", "worker:run[default]"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pubsub

  morgue-worker:
    build:
      context: .
    command: ["bin/rails", "worker:run[morgue-of-default]"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - worker

  loader:
    build:
      context: .
    command: ["bin/rails", "loader:run"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - morgue-worker

  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8681:8681"
